tke_project/myapp/urls.py
from django.urls import path, include
from . import views
from . import philan



urlpatterns = [
		path('', views.GalleryView.as_view(), name='index'),
		#path('philanthropy/', philan.index),
		path('philanthropy/', philan.EventView.as_view(), name='philanthropy'),
		path('post/', philan.CreateEventView.as_view()),
		path('photoPost/',views.CreateImageView.as_view()),
]

tke_project/tke_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings # new
from django.conf.urls.static import static # new

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tke_project/myapp/models.py
from django.db import models
from datetime import datetime 

# Create your models here.


class Event(models.Model):
    title = models.TextField()
    description = models.TextField()
    published_date = models.DateTimeField(auto_now_add=True, blank=True) #Current date
    created_date = models.DateTimeField(blank=True, null=True)  #Future Date
    max_volunteers = models.IntegerField(default=1)
    current_volunteers = models.IntegerField(default=1)
    cover = models.ImageField(upload_to='event_images/')

    status = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class Gallery(models.Model):
    title = models.TextField()
    Image = models.ImageField(upload_to='photos/')

    def __str__(self):
        return self.title

tke_project/myapp/forms.py
from django import forms
from .models import Event
from .models import Gallery
class EventForm(forms.ModelForm):

    class Meta:
        model = Event
        fields = ['title', 'description', 'created_date', 'max_volunteers', 'status', 'cover']

class GalleryForm(forms.ModelForm):

    class Meta:
        model = Gallery
        fields = ['title', 'Image']

tke_project/myapp/views.py
from django.shortcuts import render
from .models import Gallery
# Create your views here.
from django.http import HttpResponse

# Built-in Django CreateView
from django.views.generic import ListView, CreateView 

#Handle the redirect back to our homepage 
from django.urls import reverse_lazy 

# Create your views here.
from django.http import HttpResponse
from .forms import GalleryForm

def index(request):
    context = {
        "variable":"App",
        "title":"TKE",
    }
    return render(request, "index.html", context=context)

# A page representing a list of objects.
class GalleryView(ListView):
    model = Gallery
    template_name = 'index.html'

class CreateImageView(CreateView): 
    model = Gallery
    form_class = GalleryForm
    template_name = 'sections/PhotoPost.html'
    success_url = reverse_lazy('index')

tke_project/myapp/templates/base.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/foundation.css" %}">
    <link rel="stylesheet" href="{% static "css/app.css" %}">
    <link rel="stylesheet" href="{% static "css/hover.css" %}">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

    <!-- Project Stylesheet -->
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block head %}
    {% endblock %}

  </head>
  <body>
      <img src="../static/Images/TKENewLOGO.png" id="TKENewLOGO">
      <div class="top-bar">
          <div class="top-bar-center">
              <ul class="menu">
                  <li>
                    <a href="/" class="hvr-underline-from-center">Home</a>
                  </li>
                  <li>
                    <a href="#" class="hvr-underline-from-center">About Us</a>
                  </li>
                  <li>
                    <a href="/philanthropy" class="hvr-underline-from-center">Philanthropy</a>
                  </li>
                  <li>
                    <a href="#" class="hvr-underline-from-center">Contact Us</a>
                  </li>
                  <li>
                    <a href="/admin" class="hvr-underline-from-center">Log In</a>
                  </li>
                  <li>
                    <a href="#" class="hvr-underline-from-center">My Account</a>
                  </li>
              </ul>
          </div>
      </div>
    {% block header %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    <footer class="footer-distributed">

        <div class="footer-left">
  
            <img src="../static/Images/TKE-Logo.png" >
  
          <p class="footer-links">
            <a href="#" class="link-1">Home</a>
          
            <a href="#">About Us</a>
          
            <a href="#">Philanthropy</a>
            
            <a href="#">Contact Us</a>
            
            <a href="#">Log In</a>

            <a href="#">My Account</a>
          </p>
  
          <p class="footer-company-name">2019 © All Rights Reserved. <a href="#">Member Privacy</a> </p>
        </div>
  
        <div class="footer-center">
  
          <div>
            <i class="fa fa-map-marker"></i>
            <p><span>7439 Woodland Drive Suite 100</span> Indianapolis, IN 46278</p>
          </div>
  
          <div>
            <i class="fa fa-phone"></i>
            <p>+(317) 872-6533</p>
          </div>
  
          <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:tkeogc@tke.org">tkeogc@tke.org</a></p>
          </div>
  
        </div>
  
        <div class="footer-right">
  
          <p class="footer-company-about">
            <h4>About <span>TKE</span></h4>
            <div id="about-font">Founded on January 10, 1899, Tau Kappa Epsilon is one of the largest collegiate men’s social fraternities in North America with over 286,000 initiated members and 233 active chapters and colonies. TKE’s mission is to aid men in their mental, moral and social development for life. With nearly 12,000 collegiate members, Tau Kappa Epsilon contributes to the advancement of society through the personal growth of our members, and service to others. TKE builds Better Men for a Better World.</div>
          </p>
  
          <div class="footer-icons">
  
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-github"></i></a>
  
          </div>
  
        </div>
  
      </footer>
    <script src="{% static "js/vendor/jquery.js" %}"></script>
    <script src="{% static "js/vendor/what-input.js" %}"></script>
    <script src="{% static "js/vendor/foundation.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

tke_project/myapp/templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="slideshow-container">

        <!-- Full-width images with number and caption text -->
        <div class="mySlides fade">
          <div class="numbertext">1 / 3</div>
          <img src="../static/Images/work.jpg" class="imgBox">
        </div>
      
        <div class="mySlides fade">
          <div class="numbertext">2 / 3</div>
          <img src="../static/Images/crying.jpg" class="imgBox">
        </div>
      
        <div class="mySlides fade">
          <div class="numbertext">3 / 3</div>
          <img src="../static/Images/spongebob.jpg" class="imgBox">
        </div>
      
        <!-- Next and previous buttons -->
        <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
        <a class="next" onclick="plusSlides(1)">&#10095;</a>
      </div>
      <br>
      
      <!-- The dots/circles -->
      <div style="text-align:center">
        <span class="dot" onclick="currentSlide(1)"></span>
        <span class="dot" onclick="currentSlide(2)"></span>
        <span class="dot" onclick="currentSlide(3)"></span>
      </div>
      <br>

      <div class="pitch" style="text-align: center">
          <div id="earth"></div>
          <p id="whyJoin">WHY JOIN TAU KAPPA EPSILON INTERNATIONAL FRATERNITY?</p>
          <br>
          <p>Founded by Opportunity Out of Defeat and built on the honest convictions of Love, Charity and Esteem, Tau Kappa Epsilon
            is a men’s social fraternity 120 years in the making. We encourage you to take the opportunity to learn more about our brotherhood,
            available scholarships, educational programing and leadership development to see why we are the Fraternity for Life.</p>
          <br>
          <a class="button">RUSH TKE</a>
      </div>
      <div class="photo-container" align="center">
      <div class="photo-container-title" align="center">

        <h5 align="center" id="Photo-title"> Greek Week 2018 </h3>
        <br>
        <a id="photo-submit-button" href="/photoPost">Add to container</a>

      </div>
      <section id="photos">
          {% for post in object_list %}
            <img src="{{ post.Image.url}}">
        {% endfor %}
          
        </section>
    </div>
      <script src="../static/js/home.js"></script>
{% endblock %}

tke_project/myapp/templates/sections/philanthropy.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block header %}

<h4 id="event-title">Upcoming Events</h4>

<hr>
<div class="row">
        <div class="small-6 small-centered text-center columns">
                <a href="/post" class="button">Create Event</a>
        </div>
</div>

<div class="grid-x grid-margin-x small-up-2 medium-up-2 large-up-4">
        <!-- While this view is executing, self.object_list will contain the list of objects that the view is operating upon.-->
        {% for post in object_list %}
        <div class="cell">
                <h5>{{ post.title }}</h5>
                <p>{{post.description}}</p>
                <p>{{post.published_date}}</p>
                <p>{{post.created_date}}</p>
                <div class="event-container">
                        <img class="thumbnail" src="{{ post.cover.url}}" alt="{{ post.title }}">
                        <div class="event-bottom-left">{{post.current_volunteers}}/{{post.max_volunteers}}</div>
                        <div class="event-bottom-right">{{post.status}}</div>
                </div>
                <a href="#" class="button expanded">Sign Up</a>
        </div>
        {% endfor %}
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

tke_project/myapp/templates/sections/photoPost.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block header %}

<h1>Submit a Photo</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
      <div class="large-12 columns">
          <label>Title
              <input name="title" required="" id="id_title" type="text" placeholder="Title" />
          </label>
      </div>
  </div>
  <p><label for="id_cover">Photo:</label> <input type="file" name="Image" accept="image/*" required="" id="id_cover"></p>
  <button type="submit" class="alert button">Submit</button>
  </form>


{% endblock %}

{% block scripts %}

{% endblock %}

tke_project/myapp/templates/sections/post.html
{% extends "base.html" %}

{% block head %}
{% endblock %}

{% block header %}

<!-- templates/post.html -->

<!-- <h3>Create Post Page</h3>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Submit New Post</button>
</form> -->

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="large-12 columns">
            <label>Title
                <input name="title" required="" id="id_title" type="text" placeholder="Title" />
            </label>
        </div>
    </div>
    <div class="row">
          <div class="large-12 columns">
            <label>Description
              <textarea name="description" required="" id="id_description" placeholder="Description"></textarea>
            </label>
          </div>
    </div>
    <p><label for="id_cover">Cover:</label> <input type="file" name="cover" accept="image/*" required="" id="id_cover"></p>
    <div class="small-12 medium-6 columns">
      <label>
          Number of Volunteers
          <input type="number" name="max_volunteers" value="1" required="" >
      </label>
    </div>
    <p>
      <label for="id_status">Status:</label> <input type="checkbox" name="status" id="id_status" checked="">
    </p>
    <button type="submit" class="alert button">Submit New Post</button>
</form>

{% endblock %}

{% block scripts %}

{% endblock %}